+incdir+$HISOC_PATH/rtl/rvseed
$HISOC_PATH/rtl/rvseed/riscv_inst_define.v
$HISOC_PATH/rtl/rvseed/rvseed_structure_define.v
$HISOC_PATH/rtl/rvseed/rvseed_configuration_define.v
$HISOC_PATH/rtl/rvseed/mux_mem.v
$HISOC_PATH/rtl/rvseed/data_mem.v
$HISOC_PATH/rtl/rvseed/mux_reg.v
$HISOC_PATH/rtl/rvseed/regs_rvseed.v
$HISOC_PATH/rtl/rvseed/pc_reg.v
$HISOC_PATH/rtl/rvseed/ifu.v
$HISOC_PATH/rtl/rvseed/idu.v
$HISOC_PATH/rtl/rvseed/exu.v
$HISOC_PATH/rtl/rvseed/ifu2idu.v
$HISOC_PATH/rtl/rvseed/idu2exu.v
$HISOC_PATH/rtl/rvseed/rvseed.v
